version: '3'
services:

    pravo:
        container_name: pravo
        image: rgru/works:7.0.31-pravo
        network_mode: bridge
        
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/nginx/pravo.conf:/etc/nginx/sites-enabled/pravo.conf"
            - ".:/var/www/pravo"
        
        ports:
            - "3034:81"

        # Not to change db server names  when deploying to the production server.    
        external_links: 
            - mysql-com
            - mysql-com:web-db.rg.ru
            - mysql-com:g8-8-db.rg.ru
            
        # to check if the code runs inside container
        environment: 
            - INDOCKER=1

        command: >
            bash -c " 
            echo 'COMMANDS ------------------------>'
            && touch /var/www/pravo/www/app/config/parameters_db.yml
            && composer i -d /var/www/pravo/www
            && chmod -R 777  /var/www/pravo/www/var/
            && /var/www/pravo/www/bin/console cache:clear --no-warmup --env=prod
            && /var/www/pravo/www/bin/console cache:clear --no-warmup --env=dev
            && sed -i 's/^bind .*/bind 0.0.0.0/g' /etc/redis/redis.conf
            && sed -i 's/^\(protected-mode\) .*/\1 no/g' /etc/redis/redis.conf
            && redis-server /etc/redis/redis.conf
            && php-fpm & nginx -g 'daemon off;'"

        stdin_open: true
        tty: true
        restart: always
    
