#jurist_test:
#    path:     /test/
#    defaults: { _controller: JuristBundle:Test:# }

jurist_get_list_of_questions:
    path:     /questions/{rubric}/{tag}
    defaults: { _controller: JuristBundle:Question:getQuestions, rubric: null, tag: null }
    requirements:
            _method:  GET

jurist_create_question:
    path:     /question/create/
    defaults: { _controller: JuristBundle:Question:createQuestion }

jurist_get_answer:
    path:     /question/{id}/answer/
    defaults: { _controller: JuristBundle:Question:getAnswer }

rg_main_page_1: #главная
        path:     /
        defaults: { _controller: JuristBundle:Questions:main,  page: 1 }

rg_main_page_2: #главная
        path:     /main/{pageId}/
        defaults: { _controller: JuristBundle:Questions:main,  page: pageId }
        requirements:
                    _pageId: "/d+"

#rg_main_page_3: #главная тестовая
#        path:     /main1/{pageId}/
#        defaults: { _controller: JuristBundle:Questions1:main,  page: pageId }
#        requirements:
#                    _pageId: "/d+"

rg_answer_page: #вопрос-ответ
        path:     /rubrics/question/{id}/
        defaults: { _controller: JuristBundle:Answers:answer,  id: null }
        requirements:
                    _id: "/d+"

rg_jurist_page1: #страница конкретного юриста без пагинации
        path:     /jurist/{id}/
        defaults: { _controller: JuristBundle:Jurist:jurist, page: 1, id: null}
        requirements:
                    _id: "/d+"

rg_jurist_page: #страница конкретного юриста
        path:     /jurist/{pageId}/{id}/
        defaults: { _controller: JuristBundle:Jurist:jurist, page: pageId, id: null}
        requirements:
                    _id: "/d+"
                    _pageId: "/d+"

rg_jurists_page: #страница всех юристов
        path:     /jurists/{id}/
        defaults: { _controller: JuristBundle:Jurists:jurists,  id: null}
        requirements:
                    _id: "/d+"


rg_rubrics_page: # страница рубрик
        path:     /rubrics/{id}/
        defaults: { _controller: JuristBundle:Rubrics:rubric, id: 0 }
        requirements:
                    _id: "/d+"

rg_rubric_page_1: # страница конкретной рубрики
        path:     /rubric/{CPUName}/
        defaults: { _controller: JuristBundle:Rubric:rubric,  numberPage: 1 }
        requirements:
                    _CPUName: "/w+"
                    _numberPage: "/d+"

rg_rubric_page: # страница конкретной рубрики
        path:     /rubric/{numberPage}/{CPUName}/
        defaults: { _controller: JuristBundle:Rubric:rubric}
        requirements:
                    _CPUName: "/w+"
                    _numberPage: "/d+"

rg_tag_page: # страница конкретного тега
        path:     /tag/{idPage}/{id}/
        defaults: { _controller: JuristBundle:Tag:tag}
        requirements:
                    _idPage: "/d+"
                    _id: "/d+"

ask_page: # форма задачи вопроса
        path:     /ask/
        defaults: { _controller: JuristBundle:Ask:ask }

rules_page: # правила
        path:     /rules/
        defaults: { _controller: JuristBundle:Rules:rules }

partners_page: # партнеры
        path:     /partners/
        defaults: { _controller: JuristBundle:Partners:partners }

rating_page: # рейтинг вопроса
        path:     /rating/{id}/
        defaults: { _controller: JuristBundle:Rating:get, id: null}
        requirements:
                    _id: "/d+"

rg_form:
        path:     /form/{id}/
        defaults: { _controller: JuristBundle:Forms:get, id: null}
        requirements:
                    _id: "/d+"

rg_sidebar_page:
        path:     /sidebar/{format}/
        defaults: { _controller: JuristBundle:Api:sidebar, format: html}
        requirements:
                    _format: "html/json"

sort:
        path:     /sort/
        defaults: { _controller: JuristBundle:Sort:MakeSort}

search:
        path:     /search/{pageVal}/
        defaults: { _controller: JuristBundle:Search:Search, pageVal: 0}
        requirements:
                    _pageVal: "/d+"


get_robots_txt:
        path:     /get_robots/
        defaults: { _controller: JuristBundle:RobotsTxt:GetRobotsTxt}


set_robots_txt:
        path:     /set_robots/
        defaults: { _controller: JuristBundle:RobotsTxt:SetRobotsTxt}