<?php

namespace JuristBundle\Entity;

use Doctrine\ORM\EntityRepository;
use JuristBundle\Entity\Questions;

use JuristBundle\Controller\ApiController;

use JuristBundle\InterfaceCustom\createSitemapRepositoryInterface;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository implements createSitemapRepositoryInterface
{
    private $oDBALConnection;

    public function __construct($em, $class)
    {
        parent::__construct($em, $class);
        $this->oDBALConnection = $this->getEntityManager()->getConnection();
    }

    private function fetchAllQuery($sql, array $arrayAnswersId = [], array $doctrineParam = [])
    {
        $query = $this->oDBALConnection->executeQuery(
            $sql,
            $arrayAnswersId,
            $doctrineParam
        );

        $query->execute();
        return $query->fetchAll( \PDO::FETCH_ASSOC);


    }

    public function generateSiteMap()
    {
        $lastStep = ApiController::FINISHED_STEP;

        $sql = "
            SELECT q.id AS loc, a.date AS date
            FROM questions AS q 
                JOIN answers AS a ON a.question_id = q.id
            WHERE q.step = {$lastStep};
        ";
        return $this->fetchAllQuery($sql);
    }

}