<?php

namespace JuristBundle\Entity;

use Doctrine\ORM\EntityRepository;
use JuristBundle\Entity\Questions;

use JuristBundle\Controller\ApiController;

use JuristBundle\InterfaceCustom\createSitemapRepositoryInterface;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthUsersRepository extends \Doctrine\ORM\EntityRepository implements createSitemapRepositoryInterface
{
    private $oDBALConnection;

    public function __construct($em, $class)
    {
        parent::__construct($em, $class);
        $this->oDBALConnection = $this->getEntityManager()->getConnection();
    }

    private function fetchAllQuery($sql, array $arrayAnswersId = [], array $doctrineParam = [])
    {
        $query = $this->oDBALConnection->executeQuery(
            $sql,
            $arrayAnswersId,
            $doctrineParam
        );

        $query->execute();
        return $query->fetchAll( \PDO::FETCH_ASSOC);


    }

    public function generateSiteMap()
    {
        $userExceptionId = ApiController::ID_USER_WITHOUT_AVATARS;
        $userActive = ApiController::VALUE_ACTIVE_USER;

        $sql = "
            SELECT id AS loc, edit_date AS date
            FROM auth_users AS au
            WHERE au.is_jurist = true AND au.disabled = {$userActive} AND au.id != {$userExceptionId};
        ";

        return $this->fetchAllQuery($sql);
    }
}