<?php

namespace JuristBundle\Entity;

use Doctrine\ORM\EntityRepository;
use JuristBundle\Entity\Rubrics;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
/**
 * RubricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricsRepository extends \Doctrine\ORM\EntityRepository
{

    const RUBRICS = '/jurists/rubrics/';

    public function fetchRubrics($field) {
        $rubric_result = [];

        $Rubrics = $this
            ->getEntityManager()
            ->getRepository('JuristBundle:Rubrics')
            ->createQueryBuilder('r')
            ->innerJoin('r.questions', 'q')
            ->where('q.id = :questions_id')
            ->setParameter('questions_id', $field)
            ->getQuery()
            ->getArrayResult();
        foreach ($Rubrics as $rubric){
            $rubric_result[] = [
                'rubric_link' => self::RUBRICS . $rubric['id'],
                'rubric_text' => $rubric['name']
            ];
        }
        return $rubric_result;
    }
}
