<?php

namespace JuristBundle\Entity;

use Doctrine\ORM\EntityRepository;
use JuristBundle\Entity\Tags;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends \Doctrine\ORM\EntityRepository
{

    const TAGS = '/jurists/tags/';

    public function fetchTags($field) {
        $tags_result = [];

        $Tags = $this
            ->getEntityManager()
            ->getRepository('JuristBundle:Tags')
            ->createQueryBuilder('t')
            ->innerJoin('t.questions', 'q')
            ->where('q.id = :questions_id')
            ->setParameter('questions_id', $field)
            ->getQuery()
            ->getArrayResult();

        foreach ($Tags as $tag_result){
            $tags_result[] = [
                'tags_title' => $tag_result['name'],
                'tags_link' => self::TAGS . $tag_result['id']
            ];
        }
        return $tags_result;
    }
}
