<div class="b-field b-field_select">
	<div class="b-field__wrapper b-field__wrapper_inline">
		<form>
			<label>
				<select class="b-field__select b-users-sorting__select" id="order_by">
				    <option value="alphabet">По алфавиту</option>
				    <option value="rating">По рейтингу</option>
				    <option value="company">По компании</option>
				</select>
			</label>
		</form>
	</div>
</div>