args:
  default_start_uri: '/views/include/'
  default_args_tmpl: 'tmpl'
  tables:
    #Ключами в этом массиве являются из значения из uri, если вдруг надо будет поменять под стандарт RG
    tags: tags
    rubrics: rubrics
    jurists: jurists
  order_by_default_sort: DESC
  order_by_default_value: &order_by_default_value a_date DESC
  order_by_allow: ['a_date', 'au_name'] #Разрешенные поля для order_by
  allowed_args:
    order_by: *order_by_default_value
    limit: 7
    offset: 0
    tags: 0
    rubrics: 0
    jurists: 0
  limit: 7
  offset: 7
max_limit: 1000