#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

jurist_bundle:
    resource: "@JuristBundle/Resources/config/routing.yml"
    prefix:   /

#test_resource:
#        resource: "@JuristBundle/Resources/public/css/global.css"
#        type:     annotation
#        prefix:   /test/css/