# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.pagination:
          class: JuristBundle\Services\Pagination
          arguments: ["@service_container"]

      app.configer:
          class: JuristBundle\Services\Configer
          arguments: ["@service_container"]

      app.arr:
          class: JuristBundle\Services\Arr
          arguments: ["@service_container"]

      app.entity_management_guesser:
          class: JuristBundle\Services\EntityManagementGuesser
          #arguments: ["@service_container"]
