JuristBundle\Entity\Author:
    type: entity
    table: jurist.author
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        city:
            type: string
            length: '100'
    oneToMany:
            questionId:
              targetEntity: Questions
              mappedBy: authorId
    lifecycleCallbacks: {  }
