JuristBundle\Entity\Companies:
    type: entity
    table: jurist.companies
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        dateTime:
            type: datetime
            column: date_time
        createdAt:
            type: datetime
        editedAt:
            type: datetime
    manyToMany:
#        rubrics: #todo START выпелин из-за ненадобности
#            targetEntity: Rubrics
#            inversedBy: companies
#            joinTable:
#                name: jurist.companies_rubrics
#                joinColumns:
#                  companies_id:
#                    referencedColumnName: id
#                inverseJoinColumns:
#                  rubrics_id:
#                    referencedColumnName: id #todo END выпелин из-за ненадобности
        questions:
            targetEntity: Questions
            inversedBy: companies
            joinTable:
              name: jurist.companies_questions
              joinColumns:
                companies_id:
                  referencedColumnName: id
              inverseJoinColumns:
                questions_id:
                  referencedColumnName: id
        #jurists:
        #    targetEntity: Jurists
        #    inversedBy: companies
        #    joinTable:
        #      name: jurist.jurists_companies
        #      joinColumns:
        #        companies_id:
        #          referencedColumnName: id
        #      inverseJoinColumns:
        #        jurists_id:
        #          referencedColumnName: id
    oneToMany:
            #jurist: #todo
            #    targetEntity: Jurists
            #    mappedBy: companiesId
            authUsers:
                targetEntity: AuthUsers
                mappedBy: companiesId
    lifecycleCallbacks: {  }
