JuristBundle\Entity\Questions:
    type: entity
    table: jurist.questions
    repositoryClass: JuristBundle\Entity\QuestionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        AuthUsersId:
            type: integer
            column: authUsers_id
        step:
            type: smallint
            default: 0
            nullable: TRUE
        title:
            type: string
            length: '150'
        titleSeo:
            column: title_seo
            type: string
            length: '150'
            nullable: TRUE
        keywordsSeo:
            column: keywords_seo
            type: string
            length: '255'
            nullable: TRUE
        date:
            type: datetime
        description:
            type: text
            nullable: TRUE
        descriptionSeo:
            column: description_seo
            type: text
            nullable: TRUE
        status:
            type: integer
            nullable: TRUE
        deadline:
            type: datetime
            nullable: TRUE
        deadlineId:
            type: integer
            column: deadline_id
            nullable: TRUE
        deadlineInfo:
            type: integer
            column: deadline_info
            nullable: TRUE
        createdAt:
            type: datetime
            nullable: TRUE
        editedAt:
            type: datetime
            nullable: TRUE
    oneToOne:
        answersId:
            targetEntity: Answers
            mappedBy: question
    manyToOne:
        authorId:
          targetEntity: Author
          joinColumn:
            name: author_id
            referencedColumnName: id
    manyToMany:
        tags:
          targetEntity: Tags
          mappedBy: questions
        rubrics:
          targetEntity: Rubrics
          mappedBy: questions
    lifecycleCallbacks: {  }
