JuristBundle\Entity\VoteIp:
    type: entity
    table: jurist.vote_ip
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ip:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
