<!-- Rating@Mail.ru -->
<div id="mailruCounter" class="b-counter__item"></div>
<noscript><img src="//top-fwz1.mail.ru/counter?id=11659;js=na" style="border:0;position:absolute;left:-10000px;" height="1" width="1" alt="MailRu" /></noscript>
<!-- /Rating@Mail.ru -->

<!-- yaMetrika counter -->
<div id="yaMetrika"></div>
<noscript><img src="//mc.yandex.ru/watch/22322746" style="position:absolute; left:-9999px;" alt="yaMetrika"></noscript>
<!-- /yaMetrika counter -->